version: '3.8'

services:
  frontend-app:
    build: .
    container_name: frontend-cont 
    ports:
      - '3000:3000'
    depends_on:
      - mongodb  
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myDatabase
      - SESSION_SECRET=1234
      - PORT=3000
      - EMAIL_USER=chagantyteja2502@gmail.com
      - EMAIL_PASS=yxoq bjuk rdnt alzp  
  mongodb:
    image: mongo:latest 
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
